# Generated by Django 5.0.7 on 2024-07-25 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('zipcode', models.IntegerField()),
                ('photo', models.ImageField(default='default_photo.jpg', upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outgoing', models.BooleanField()),
                ('incoming', models.BooleanField()),
                ('body', models.CharField(max_length=2500)),
                ('from_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='moto.profile')),
                ('to_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='moto.profile')),
            ],
        ),
        migrations.CreateModel(
            name='MeetUpEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(max_length=2500)),
                ('invite_only', models.BooleanField()),
                ('main_image', models.ImageField(default='default_photo.jpg', upload_to='photos/')),
                ('images', models.ImageField(default='default_photo.jpg', upload_to='photos/')),
                ('category', models.CharField(max_length=500)),
                ('skill_level', models.CharField(max_length=75)),
                ('location', models.CharField(max_length=75)),
                ('type', models.CharField(max_length=30)),
                ('tags', models.CharField(max_length=200)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetup_events', to='moto.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('tags', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=2500)),
                ('images', models.ImageField(default='default_photo.jpg', upload_to='photos/')),
                ('links', models.CharField(max_length=2500)),
                ('category', models.CharField(max_length=500)),
                ('first_choice', models.CharField(blank=True, max_length=150, null=True)),
                ('second_choice', models.CharField(blank=True, max_length=150, null=True)),
                ('votes1', models.FloatField(blank=True, default=0, null=True)),
                ('votes2', models.FloatField(blank=True, default=0, null=True)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to='moto.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=2500)),
                ('image', models.ImageField(default='default_photo.jpg', upload_to='photos/')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='moto.forumpost')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='moto.profile')),
            ],
        ),
    ]
