# Generated by Django 5.0.7 on 2024-07-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0003_remove_forumpost_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='category',
            field=models.ManyToManyField(related_name='forum_posts', to='moto.category'),
        ),
        migrations.AddField(
            model_name='meetupevent',
            name='category',
            field=models.ManyToManyField(related_name='meetup_events', to='moto.category'),
        ),
    ]
